### ISSUE TITLE
Not loading mixed contents

### ISSUE THREAD

**Issue by myfrndjk** [pfraze/electron-browser#3]
Hi,
I am seeing the below errors on the most of the websites.

Mixed Content: The page at 'https://www.whatismyip.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lora'. This request has been blocked; the content must be served over HTTPS.

Thanks
Jk

**Comment by pfrazee** [comment]
Yeah there's a way to modify this policy, but it's not yet exposed to webviews by electron. I'm working on a PR to electron to solve it.

**Comment by myfrndjk** [comment]
Could you please tell me how to modify this policy.
some sites are completely broken due to this issue, since they render all the images from http:// schema .

**Comment by pfrazee** [comment]
It's going to require a PR to electron, which is upstream of this project. I started a PR for it (https://github.com/electron/electron/pull/7431) but the maintainer asked for changes, and I haven't had the time to make them yet.

**Comment by myfrndjk** [comment]
Resolving this since since issue is fixed upstream
