### ISSUE TITLE
Content isn't loaded

### ISSUE THREAD

**Issue by jerone** [pfraze/electron-browser#6]
When running this project I'm getting a great browser ui, but the webview stays empty, no-matter where I navigate too. Should this work?

![2016-11-08 16_17_42-browser html](https://cloud.githubusercontent.com/assets/55841/20104583/d1111f1a-a5ce-11e6-97fe-608d0d79222e.png)

_Windows 8.1_
_Node.js v6.9.0_

**Comment by pfrazee** [comment]
Hmm! That's a shame. I'm not actively supporting this project anymore, but if you find a fix, I'm happy to merge the PR.

I work now on [beaker browser](https://github.com/beakerbrowser/beaker), which is a much better featured electron-based browser, and still very forkable. It doesn't build on windows yet, but I'm happy to work with you to make that happen.

**Comment by jerone** [comment]
The weird thing is that it works on Windows 7.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over (almost) a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.

**Comment by pfrazee** [comment]
@jerone if you're interested in taking over this project, I'm happy to give commit access

**Comment by jerone** [comment]
[**@pfrazee**](https://github.com/pfrazee) commented on [Sep 18, 2017, 5:34 PM GMT+2](https://github.com/pfrazee/electron-browser/issues/6#issuecomment-330261900 "2017-09-18T15:34:24Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone) if you're interested in taking over this project, I'm happy to give commit access

No, sorry. I have moved on to other projects.

**Comment by pfrazee** [comment]
All good, so have I
