### ISSUE TITLE
What should I do if I want to define a global variable that can be used within the page?

### ISSUE THREAD

**Issue by PikachuWu** [pfraze/electron-browser#9]

**Comment by pfrazee** [comment]
Look into the preload scripts of webviews in the electron docs

**Comment by PikachuWu** [comment]
Thank you By the way, what do I need to do if I want to package this program as a Windows installation package?

**Comment by PikachuWu** [comment]
![image](https://user-images.githubusercontent.com/13596426/30677267-5bd939f6-9ebd-11e7-9040-13874652685c.png)

I packaged it through electron-packager and then opened the EXE file as shown in the picture

**Comment by pfrazee** [comment]
Sorry! Wish I could help you but this project isn't actively maintained.
